<h2>Últimos Posts</h2>
<pre><?php //print_r($this->posts); ?></pre>
<?php if (isset($this->posts) && count($this->posts)): ?>
    <table>
        <thead>
            <tr>
                <?php for ($i = 0; $i < count($this->columnas); $i++): ?>
                    <th><?php echo $this->columnas[$i]; ?></th>
                <?php endfor; ?>
            </tr>    
        </thead>
        <?php for ($i = 0; $i < count($this->posts); $i++): ?>
            <tr>
                <td><?php echo $this->posts[$i]['id'] ?></td>
                <td><?php echo $this->posts[$i]['titulo'] ?></td>
                <td><?php echo $this->posts[$i]['cuerpo'] ?></td>
                
<?php if(Session::accesoView('especial')):?>
                <td><a href="<?php echo BASE_URL . 'post/editar/' . $this->posts[$i]['id'] ?>">Editar</a></td>
                <td><a href="<?php echo BASE_URL . 'post/eliminar/' . $this->posts[$i]['id'] ?>">Eliminar</a></td>
                
<?php endif; ?>
            </tr>
        <?php endfor; ?>
    </table>
<?php else: ?>
No hay posts
<?php endif; ?>


<?php if(isset($this->paginacion)) echo $this->paginacion;?>

<?php if(Session::accesoView('especial')):?>
<p><a href="<?php echo BASE_URL;?>post/nuevo">Agregar post</a> | 
    <a href="<?php echo BASE_URL;?>post/crear100">Crear 100 posts</a> | 
    <a href="<?php echo BASE_URL;?>post/borrarPruebas">Borrar pruebas</a></p>
<?php endif; ?>

